### ISSUE TITLE
PHP 7.3?

### ISSUE THREAD

**Issue by Frederick888** [aptible/docker-php#33]
PHP 7.3 has been out for quite a while. Any plans to add it to this repo?

**Comment by UserNotFound** [comment]
Hi @Frederick888, Historically, there’s one specific reason the aptible/php images exist:  by default, PHP 5.6, 7.0, and 7.1 could not connect to Enclave MySQL databases, since we use self-signed certificates.  There was no way to override this behavior at the time: https://bugs.php.net/bug.php?id=71003

So, we patched PHP ourselves to allow disabling certificate verification: https://github.com/aptible/docker-php/pull/1/commits/dff6745cdbc0b36ad41d19c39b08e819a0702dbd

Eventually this patch got mainlined, but only in PHP 7.0+, so we continued to provide the this image even though the only useful contribution were making is only applied to PHP 5.6: https://github.com/aptible/docker-php/commit/667de008157a6039051621b8e6155bee63a30c4b

PHP 5.6 was EOL’ed in December, so our plan is to deprecate this repository rather than continue to maintain it by supplying newer releases.
